[package]
name = "texture_stacker_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.5"
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.9"
